---
language: python
services: docker
cache:
  pip: true

install:
  - pip install pipenv
  - pipenv install

#before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  #- cd ../
  #- mv 389ds-server lvps.389ds-server
  #- cd lvps.389ds-server

script:
  - molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
