---
- hosts: localhost

  tasks:
    - name: Copy ldif
      template: src=templates/supplier_init_consumer.ldif.j2 dest=/root/supplier_init_consumer.ldif

    - name: Initializing consumer from supplier
      shell: ldapmodify -D {{ rootdn }} -w {{ password }} -h localhost -v < /root/supplier_init_consumer.ldif
      register: results
      failed_when:  not((results.rc == 0)or(results.rc == 68))
      changed_when: results.rc == 0
