---
- name: Remove temporary files
  file: path={{ item }} state=absent
  with_items:
   - /root/roreplica.ldif
   - /root/replication_user.ldif
   - /root/master_changelog.ldif
   - /root/master_replica.ldif
   - /root/master_replication_agreement.ldif
   - /root/master_init_replica.ldif
