---
- include: configure_replication_user.yaml

- name: Copy installation templates
  template: src=templates/{{ item }}.j2 dest=/root/{{ item }}
  with_items:
   - master_changelog.ldif
   - master_replica.ldif
   - master_replication_agreement.ldif
   - master_init_replica.ldif

- name: Configure replication master changelog
  shell: ldapmodify -D {{ rootdn }} -w {{ password }} -h localhost -v -f /root/master_changelog.ldif
  register: results
  failed_when: not((results.rc == 0)or(results.rc == 68))
  changed_when: results.rc == 0

- name: Configuring replication master replica
  shell: ldapmodify -D {{ rootdn }} -w {{ password }} -h localhost -v -f /root/master_replica.ldif
  register: results
  failed_when: not((results.rc == 0)or(results.rc == 68)or('replica already configured for' in results.stderr))
  changed_when: results.rc == 0

- name: Configuring replication agreement
  shell: ldapmodify -D {{ rootdn }} -w {{ password }} -h localhost -v -f /root/master_replication_agreement.ldif
  register: results
  failed_when: not((results.rc == 0)or(results.rc == 68))
  changed_when: results.rc == 0

- name: Initializing replica from master
  shell: ldapmodify -D {{ rootdn }} -w {{ password }} -h localhost -v -f /root/master_init_replica.ldif
  register: results
  failed_when:  not((results.rc == 0)or(results.rc == 68))
  when: init_replica
  changed_when: results.rc == 0
