---
- include: configure_replication_user.yaml

- name: Copy ldif templates
  template: src=templates/{{ item }}.j2 dest=/root/{{ item }}
  with_items:
   - roreplica.ldif

- name: Configure roreplica
  shell: ldapmodify -D {{ rootdn }} -w {{ password }} -h localhost -v -f /root/roreplica.ldif
  register: results
  failed_when: not((results.rc == 0)or(results.rc == 68))
  when: not rwmaster
  changed_when: results.rc == 0
