---
- name: Configure MemberOf plugin
  ldap_attr:
    server_uri: "ldap:///localhost"
    bind_dn: "{{ rootdn }}"
    bind_pw: "{{ rootdn_password }}"
    dn: "cn=MemberOf Plugin,cn=plugins,cn=config"
    name: nsslapd-pluginEnabled
    values: "{{ 'on' if plugins.memberof.enabled else 'off' }}"
    state: exact

- name: Configure DNA plugin
  ldap_attr:
    server_uri: "ldap:///localhost"
    bind_dn: "{{ rootdn }}"
    bind_pw: "{{ rootdn_password }}"
    dn: "cn=Distributed Numeric Assignment Plugin,cn=plugins,cn=config"
    name: "{{ item.name }}"
    values: "{{ item.value }}"
    state: exact
  loop:
  - { name: "nsslapd-pluginEnabled", value: "{{ 'on' if plugins.dna.enabled else 'off' }}" }
  notify: dirsrv restart # TODO: is this really needed? Check the manual

# TODO: make this "UID numbers/GID numbers" generic (if possible at all)
- name: Remove DNA plugin configuration (if disabled)
  ldap_entry:
    server_uri: "ldap:///localhost"
    bind_dn: "{{ rootdn }}"
    bind_pw: "{{ rootdn_password }}"
    dn: "{{ item }}"
    state: absent
  loop:
  - "cn=UID numbers,cn=Distributed Numeric Assignment Plugin,cn=plugins,cn=config"
  - "cn=GID numbers,cn=Distributed Numeric Assignment Plugin,cn=plugins,cn=config"
  when: not plugins.dna.enabled
  notify: dirsrv restart # TODO: is this really needed? Check the manual

- name: Create DNA plugin configuration (if enabled)
  ldap_entry:
    server_uri: "ldap:///localhost"
    bind_dn: "{{ rootdn }}"
    bind_pw: "{{ rootdn_password }}"
    dn: "{{ item }}"
    objectClass:
      - top
      - extensibleObject
    state: present
  loop:
  - "cn=UID numbers,cn=Distributed Numeric Assignment Plugin,cn=plugins,cn=config"
  - "cn=GID numbers,cn=Distributed Numeric Assignment Plugin,cn=plugins,cn=config"
  when: plugins.dna.enabled
  notify: dirsrv restart # TODO: is this really needed? Check the manual

- name: Configure DNA plugin parameters (UID)
  ldap_attr:
    server_uri: "ldap:///localhost"
    bind_dn: "{{ rootdn }}"
    bind_pw: "{{ rootdn_password }}"
    dn: "cn=UID numbers,cn=Distributed Numeric Assignment Plugin,cn=plugins,cn=config"
    name: "{{ item.name }}"
    values: "{{ item.value }}"
    state: exact
  loop:
  - { name: "cn", value: "UID numbers" }
  - { name: "dnatype", value: "uidNumber" }
  - { name: "dnamagicregen", value: "99999" } # TODO: what does this mean? Check the manual
  - { name: "dnafilter", value: "(objectclass=posixAccount)" }
  - { name: "dnascope", value: "{{ suffix }}" }
  - { name: "dnanextvalue", value: "{{ plugins.dna.uid_min }}" }
  - { name: "dnamaxvalue", value: "{{ plugins.dna.uid_max }}" }
  when: plugins.dna.enabled
  notify: dirsrv restart # TODO: is this really needed? Check the manual

- name: Configure DNA plugin parameters (GID)
  ldap_attr:
    server_uri: "ldap:///localhost"
    bind_dn: "{{ rootdn }}"
    bind_pw: "{{ rootdn_password }}"
    dn: "cn=GID numbers,cn=Distributed Numeric Assignment Plugin,cn=plugins,cn=config"
    name: "{{ item.name }}"
    values: "{{ item.value }}"
    state: exact
  loop:
  - { name: "cn", value: "GID numbers" }
  - { name: "dnatype", value: "gidNumber" }
  - { name: "dnamagicregen", value: "99999" } # TODO: what does this mean? Check the manual
  - { name: "dnafilter", value: "(objectclass=posixAccount)" }
  - { name: "dnascope", value: "{{ suffix }}" }
  - { name: "dnanextvalue", value: "{{ plugins.dna.gid_min }}" }
  - { name: "dnamaxvalue", value: "{{ plugins.dna.gid_max }}" }
  when: plugins.dna.enabled
  notify: dirsrv restart # TODO: is this really needed? Check the manual
