---
- include: configure_replication_user.yaml

- name: Copy ldif templates
  template: src=templates/{{ item }}.j2 dest=/root/{{ item }}
  with_items:
   - consumer_replica.ldif

- name: Configure consumer replica
  shell: ldapmodify -D {{ rootdn }} -w {{ password }} -h localhost -v < /root/consumer_replica.ldif
  register: results
  failed_when: not((results.rc == 0)or(results.rc == 68))
  when: not supplier
  changed_when: results.rc == 0
