---
- name: Copy installation templates
  template: src=templates/{{ item }}.j2 dest=/root/{{ item }}
  with_items:
   - supplier_changelog.ldif
   - supplier_replica.ldif
   - supplier_replication_agreement.ldif
   - supplier_init_consumer.ldif

- name: Configure replication supplier changelog
  shell: ldapmodify -D {{ rootdn }} -w {{ password }} -h localhost -v < /root/supplier_changelog.ldif
  register: results
  failed_when: not((results.rc == 0)or(results.rc == 68))
  changed_when: results.rc == 0

- name: Configuring replication supplier replica
  shell: ldapmodify -D {{ rootdn }} -w {{ password }} -h localhost -v < /root/supplier_replica.ldif
  register: results
  failed_when: not((results.rc == 0)or(results.rc == 68)or('replica already configured for' in results.stdeer))
  changed_when: results.rc == 0

- name: Configuring replication agreement
  shell: ldapmodify -D {{ rootdn }} -w {{ password }} -h localhost -v < /root/supplier_replication_agreement.ldif
  register: results
  failed_when: not((results.rc == 0)or(results.rc == 68))
  changed_when: results.rc == 0

- name: Initializing consumer from supplier
  shell: ldapmodify -D {{ rootdn }} -w {{ password }} -h localhost -v < /root/supplier_init_consumer.ldif
  register: results
  failed_when:  not((results.rc == 0)or(results.rc == 68))
  when: init_consumer
  changed_when: results.rc == 0
