---
- name: copy private cert
  copy:
    content: "{{ tls_key }}"
    dest: "/root/{{ tls_cn }}.key"

- name: copy public cert chain
  copy:
    content: "{{ tls_cert }}"
    dest: "/root/{{ tls_cn }}.crt"

- name: copy public cert chain to ca-trust
  copy:
    content: "{{ tls_cert }}"
    dest: "/etc/pki/ca-trust/source/anchors/{{ tls_cn }}.crt"

- name: Add public cert to ca trust
  shell: "/bin/update-ca-trust"

- name: Create pkcs12
  openssl_pkcs12:
    action: export
    path: "/root/{{ tls_cn }}.p12"
    friendly_name: "{{ tls_cn }}"
    privatekey_path: "/root/{{ tls_cn }}.key"
    certificate_path: "/root/{{ tls_cn }}.crt"
    state: present

- name: Add pkcs12 to certutil
  shell: "/bin/pk12util -i /root/{{ tls_cn }}.p12 -d /etc/dirsrv/slapd-{{ serverid }} -K '' -W ''"

- name: Copy ldif templates for tls
  template: src=templates/{{ item }}.j2 dest=/root/{{ item }}
  with_items:
   - nsslapd_security.ldif
   - nssslclientauth.ldif
   - nsssl3.ldif
   - nsssl2.ldif
   - rsa-encryption.ldif

# ldapcompare cannot be used on cn=config https://pagure.io/389-ds-base/issue/49390
- name: Set nsslapd-security
  shell: ldapmodify -D {{ rootdn }} -w {{ password }} -h localhost -v < /root/nsslapd_security.ldif
  register: results
  failed_when: not((results.rc == 0)or(results.rc == 68))
  changed_when: results.rc == 0

- name: Set nssslclientauth
  shell: ldapmodify -D {{ rootdn }} -w {{ password }} -h localhost -v < /root/nssslclientauth.ldif
  register: results
  failed_when: not((results.rc == 0)or(results.rc == 68))
  changed_when: results.rc == 0

- name: Set nsssl3
  shell: ldapmodify -D {{ rootdn }} -w {{ password }} -h localhost -v < /root/nsssl3.ldif
  register: results
  failed_when: not((results.rc == 0)or(results.rc == 68))
  changed_when: results.rc == 0

- name: Set nsssl2
  shell: ldapmodify -D {{ rootdn }} -w {{ password }} -h localhost -v < /root/nsssl2.ldif
  register: results
  failed_when: not((results.rc == 0)or(results.rc == 68))
  changed_when: results.rc == 0

- name: Set rsa-encryption
  shell: ldapmodify -D {{ rootdn }} -w {{ password }} -h localhost -v < /root/rsa-encryption.ldif
  register: results
  failed_when: not((results.rc == 0)or(results.rc == 68))
  changed_when: results.rc == 0
  notify: dirsrv restart
