---
- name: Install 389DS
  yum:
    name: 389-ds-base
    state: latest

# as suggested by Red Hat Directory Server manual
- name: Add user 'dirsrv'
  user:
    name: dirsrv
    group: dirsrv
    comment: System user for 389DS
    shell: /sbin/nologin
    system: true
    create_home: false

- name: Check if instance directory exists
  stat:
    path: "/var/lib/dirsrv/slapd-{{ dirsrv_serverid }}"
  register: dirsrv_instance_dir

- set_fact:
    dirsrv_instance_dir_exists: "{{ dirsrv_instance_dir.stat.exists and dirsrv_instance_dir.stat.isdir }}"

# TODO: How do we change the Directory Manager password if we need it to change the password?
- block:
    - name: Copy installation template
      template:
        src: templates/install.inf.j2
        dest: /tmp/install.inf
        mode: '600'
      when: not dirsrv_instance_dir_exists

    - name: Copy additional ldif files
      copy:
        src: "{{ item }}"
        dest: "/tmp/{{ item | basename }}"
        mode: '400'
      when: not dirsrv_instance_dir_exists
      loop: "{{ dirsrv_install_additional_ldif }}"

    # This will install the Directory Server *only*.
    # No Configuration Directory Server: it's documented but it doesn't really exist (it's part of the Administration Server).
    # No Administration Server: it isn't worth the effort.
    - name: Run installation script setup-ds.pl
      shell: /usr/sbin/setup-ds.pl -s -f /tmp/install.inf
      when: not dirsrv_instance_dir_exists

  always:
    - name: Remove installation template
      file:
        state: absent
        path: /tmp/install.inf

- name: Start and enable 389DS {{ dirsrv_serverid }} instance
  become: true
  service:
    name: "dirsrv@{{ dirsrv_serverid }}"
    state: started
    enabled: yes

# The setup script starts the server itself, but the service/target
# still needs to be enabled. In my tests I've found that enabling
# dirsrv@serverid is not enough, it still doesn't start automatically...
- name: Enable systemd target
  become: true
  service:
    name: dirsrv.target
    enabled: yes
