---
- include: install_389ds.yaml
  when: false # TODO: remove this (for quick and dirty testing)

  # TODO: https://docs.ansible.com/ansible/latest/modules/ldap_attr_module.html
  # Use the "params" thing to pass auth data
- include: configure_logging.yaml
  when: false # TODO: remove this (for quick and dirty testing)

- include: configure_plugins.yaml
  when: false # TODO: remove this (for quick and dirty testing)

- include: configure_tls.yaml
  when: security.tls_enabled

- include: configure_replication_replica.yaml
  when: false # roreplica

- include: configure_replication_master.yaml
  when: false # rwmaster

#- include: cleanup.yaml

- include: configure_firewall.yaml
  when: false
