---
# TODO: cn=config contains nsslapd-requiresrestart, a list of things that need a restart. Check that all of them have "notify: dirsrv restart"...

# TODO: are nsCertFile and nsKeyFile still allowed, instead of the NSS database which is nearly impossible to handle correctly?
# https://www.port389.org/docs/389ds/howto/howto-ssl.html

- include: install_389ds.yaml
  when: false # TODO: remove this (for quick and dirty testing)

- name: Prepare LDAP auth data
  set_fact:
    ldap_auth:
      server_uri: "ldap://localhost"
      validate_certs: false
      start_tls: true
      bind_dn: "{{ rootdn }}"
      bind_pw: "{{ rootdn_password }}"

- include: configure_ldapi.yaml

- include: configure_logging.yaml
  when: false # TODO: remove this (for quick and dirty testing)

- include: configure_plugins.yaml
  when: false # TODO: remove this (for quick and dirty testing)

- include: configure_tls.yaml

- include: configure_replication_replica.yaml
  when: false # roreplica

- include: configure_replication_master.yaml
  when: false # rwmaster

#- include: cleanup.yaml

- include: configure_firewall.yaml
  when: false
