---
- include: prepare_server.yaml
  when: not skip_config

- include: configure_ldap_server.yaml
  when: not skip_config

- include: configure_logging.yaml
  when: not skip_config

- include: configure_plugins.yaml
  when: not skip_config

- include: configure_tls.yaml
  when: not skip_config

- include: configure_replication_replica.yaml
  when: roreplica

- include: configure_replication_master.yaml
  when: rwmaster

- include: cleanup.yaml
