---
- include: install_389ds.yaml
  when: not skip_config

  # TODO: https://docs.ansible.com/ansible/latest/modules/ldap_attr_module.html
  # Use the "params" thing to pass auth data
- include: configure_logging.yaml
  when: not skip_config

- include: configure_plugins.yaml
  when: not skip_config

- include: configure_tls.yaml
  when: not skip_config

- include: configure_replication_replica.yaml
  when: roreplica

- include: configure_replication_master.yaml
  when: rwmaster

- include: cleanup.yaml

- include: configure_firewall.yaml
  when: not skip_config
