---
- include: prepare_server.yaml
  when: not skip_config

- include: configure_ldap_server.yaml
  when: not skip_config

- include: configure_tls.yaml
  when: not skip_config

- include: configure_replication_consumer.yaml
  when: consumer

- include: configure_replication_supplier.yaml
  when: supplier

- include: cleanup.yaml
