---
- name: Converge
  hosts: all

  pre_tasks:
    # The following two tasks when executed together are always idempotent (as they replace the same file with the same content) but they register as changed
    # from Ansible's perspective. Since there is no easy way to determine wether the existing file is the original binary or the replacement script (checksum
    # matching is not possible as both the systemctl binary and the replacement script might be updated at any time in the future) then the only option is to
    # force the two tasks to not change.
    - name: Remove systemctl binary
      become: true
      file:
        path: /usr/bin/systemctl
        state: absent
      changed_when: false

    - name: Implant systemctl replacement
      become: true
      uri:
        creates: /usr/local/bin/systemctl
        dest: /usr/bin/systemctl
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx
        url: https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl.py
      changed_when: false

    - name: Create dirsrv service dropin directory
      file:
        path: /etc/systemd/system/dirsrv@.service.d/
        owner: root
        group: root
        mode: "u=rwx,g=rx,o=rx"
        state: directory

    - name: Copy dirsrv service dropin config
      become: true
      copy:
        src: dirsrv-dropin.conf
        dest: /etc/systemd/system/dirsrv@.service.d/custom.conf
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
        force: true

  roles:
    -
      role: 389ds-server
      dirsrv_suffix: "dc=example,dc=local"
      dirsrv_serverid: test
      dirsrv_rootdn_password: P455W0RD
      dirsrv_listen_host: 0.0.0.0
      dirsrv_tls_enabled: false
