---
- name: Converge
  hosts: all

  roles:
    -
      role: 389ds-server
      dirsrv_suffix: "dc=example,dc=local"
      dirsrv_serverid: test
      dirsrv_rootdn_password: secret
      dirsrv_tls_enabled: false
